name: demyx/utilities

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  master:
    runs-on: ubuntu-latest
    env:
      DEMYX_REPOSITORY: utilities
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: demyx
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: |
          docker pull ubuntu
          docker build -t demyx/${{ env.DEMYX_REPOSITORY }} .
      - name: Test
        id: test
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker run -d --name=${{ env.DEMYX_REPOSITORY }} --entrypoint=top demyx/${{ env.DEMYX_REPOSITORY }}

          DEMYX_TEST="$(docker exec ${{ env.DEMYX_REPOSITORY }} maldet -v 2>&1)"
          if [[ "$DEMYX_TEST" == *"Linux Malware Detect"* ]]; then
            echo "$DEMYX_TEST"
          else
            exit 1
          fi
      - name: Version
        run: |
          DEMYX_UTILITIES_DEBIAN_VERSION="$(docker exec ${{ env.DEMYX_REPOSITORY }} cat /etc/debian_version)"
          DEMYX_UTILITIES_MALDET_VERSION="$(docker exec ${{ env.DEMYX_REPOSITORY }} maldet -v | sed -n 1p | awk -F ' ' '{print $4}' | sed 's|v||g')"
          DEMYX_JQ="$(jq ".debian = \"$DEMYX_SSH_ALPINE_VERSION\"" version.json)"

          # Update versions
          echo "$DEMYX_JQ" > version.json
          echo "DEMYX_UTILITIES_DEBIAN_VERSION=$DEMYX_UTILITIES_DEBIAN_VERSION
          DEMYX_UTILITIES_MALDET_VERSION=$DEMYX_UTILITIES_MALDET_VERSION" > VERSION
      - name: Push
        run: |
          # Not sure why this is being created?
          [[ -f typescript ]] && rm -f typescript

          DEMYX_CHECK_STATUS="$(git status)"
          if [[ "$DEMYX_CHECK_STATUS" != *"nothing to commit"* ]]; then
            git config --global user.name github-actions[bot]
            git config --global user.email github-actions[bot]@users.noreply.github.com
            git remote set-url origin https://demyxsh:${{ secrets.DEMYX_TOKEN }}@github.com/demyxsh/${{ env.DEMYX_REPOSITORY }}
            git add .
            git commit -m "Scheduled Build"
            git push
          fi

          docker push demyx/${{ env.DEMYX_REPOSITORY }}
